###
GET http://localhost:8080/foo?param=1
###
GET http://localhost:8080/foo?param=2
###
GET http://localhost:8080/foo-suspend?param=1
###
GET http://localhost:8080/foo-suspend?param=2
###
GET http://localhost:8080/bar
###
GET http://localhost:8080/bar-suspend
